import { useState } from "react";

function RiskBadge({ level }) {
  return <span className={`badge badge-${level}`}>{level} risk</span>;
}

function ContractTypeBadge({ contractType }) {
  return <span className="badge badge-contract">📄 {contractType}</span>;
}

export default function RiskReport({ analysis, activeClauseIndex, onClauseClick }) {
  const safetyTone =
    analysis.safety_score >= 70 ? "safe" : analysis.safety_score >= 40 ? "caution" : "danger";
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    const lines = [
      "CONTRACT RISK REPORT",
      `Contract type: ${analysis.contract_type}`,
      `Overall risk: ${analysis.overall_risk}`,
      `Safety score: ${analysis.safety_score}/100`,
      "",
      "SUMMARY",
      analysis.summary,
      "",
      `RISKY CLAUSES (${analysis.clauses.length})`,
    ];

    analysis.clauses.forEach((clause, index) => {
      lines.push("");
      lines.push(`Clause ${index + 1} [${clause.risk_level} risk]`);
      lines.push(`"${clause.clause_text}"`);
      lines.push(`Why it matters: ${clause.explanation}`);
      lines.push(`Suggestion: ${clause.suggestion}`);
    });

    lines.push("");
    lines.push("Generated by Legal Clause Risk Analyzer");

    const reportText = lines.join("\n");

    const showCopiedState = () => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    };

    const fallbackCopy = () => {
      const textarea = document.createElement("textarea");
      textarea.value = reportText;
      textarea.setAttribute("readonly", "");
      textarea.style.position = "fixed";
      textarea.style.opacity = "0";
      textarea.style.pointerEvents = "none";
      document.body.appendChild(textarea);
      textarea.focus();
      textarea.select();

      try {
        const successful = document.execCommand("copy");
        if (successful) {
          showCopiedState();
        }
      } finally {
        document.body.removeChild(textarea);
      }
    };

    if (navigator.clipboard?.writeText && window.isSecureContext) {
      navigator.clipboard
        .writeText(reportText)
        .then(showCopiedState)
        .catch(fallbackCopy);
      return;
    }

    fallbackCopy();
  };

  return (
    <div className="report">
      <div className="score-panel">
        <div className={`score-ring score-${safetyTone}`}>
          <span>{analysis.safety_score}</span>
        </div>
        <div>
          <p className="section-kicker">Safety score</p>
          <h3 className="score-title">Contract safety score</h3>
          <p className="score-explainer">{analysis.safety_score_explanation}</p>
        </div>
      </div>

      <div className="report-header">
        <div>
          <p className="section-kicker">Analysis result</p>
          <h2>Your contract risk report</h2>
        </div>
        <div className="report-badges">
          <button
            type="button"
            className="secondary-button copy-button"
            onClick={handleCopy}
          >
            {copied ? "✅ Copied!" : "📋 Copy report"}
          </button>
          <ContractTypeBadge contractType={analysis.contract_type} />
          <RiskBadge level={analysis.overall_risk} />
        </div>
      </div>

      <p className="summary-card">{analysis.summary}</p>

      {analysis.clauses.length === 0 ? (
        <div className="empty-state">No significant risks found ✅</div>
      ) : (
        <div className="clause-list">
          {analysis.clauses.map((clause, index) => (
            <article
              className={`clause-card ${activeClauseIndex === index ? "clause-card-active" : ""}`}
              key={`${clause.clause_text}-${index}`}
              onClick={() => onClauseClick(activeClauseIndex === index ? null : index)}
              style={{ cursor: "pointer" }}
            >
              <div className="clause-topline">
                <h3>Clause {index + 1}</h3>
                <RiskBadge level={clause.risk_level} />
              </div>
              <blockquote>{clause.clause_text}</blockquote>
              <p>{clause.explanation}</p>
              <p className="suggestion">
                <em>💡 Suggestion: {clause.suggestion}</em>
              </p>
            </article>
          ))}
        </div>
      )}
    </div>
  );
}
